"""
Example Library for 10 Orthogonal Cognitive Domains

Contains 150 worked examples (15 per domain) from established benchmarks:
- GSM8K, HumanEval, BIG-Bench, MMLU, TriviaQA, ARC, etc.

Each example includes:
- Problem statement
- Solution approach
- Step-by-step solution
- Final answer
"""

from dataclasses import dataclass
from typing import List, Dict, Optional
from .domains import DomainType


@dataclass
class WorkedExample:
    """A worked example with problem and solution."""

    id: str
    domain: DomainType
    subcategory: str
    difficulty: str  # "easy", "medium", "hard"
    problem: str
    approach: str
    steps: List[str]
    answer: str
    source: str  # Dataset it came from

    def to_prompt_text(self) -> str:
        """Convert example to text for agent prompt."""
        steps_text = "\n".join(f"  {i+1}. {step}" for i, step in enumerate(self.steps))
        return f"""**Example ({self.difficulty})**:
Problem: {self.problem}
Approach: {self.approach}
Steps:
{steps_text}
Answer: {self.answer}"""

    def to_short_text(self) -> str:
        """Short version for prompt space efficiency."""
        return f"• {self.problem[:100]}... → {self.answer}"


class ExampleLibrary:
    """Library of 150 worked examples across 10 domains."""

    def __init__(self):
        self._examples: Dict[str, WorkedExample] = {}
        self._by_domain: Dict[DomainType, List[WorkedExample]] = {d: [] for d in DomainType}
        self._load_all_examples()

    def _load_all_examples(self):
        """Load all 150 examples."""
        all_examples = (
            self._arithmetic_examples() +
            self._algorithmic_examples() +
            self._factual_examples() +
            self._procedural_examples() +
            self._creative_examples() +
            self._summarization_examples() +
            self._causal_examples() +
            self._analogical_examples() +
            self._coding_examples() +
            self._scientific_examples()
        )

        for ex in all_examples:
            self._examples[ex.id] = ex
            self._by_domain[ex.domain].append(ex)

    def get(self, example_id: str) -> Optional[WorkedExample]:
        """Get an example by ID."""
        return self._examples.get(example_id)

    def get_by_domain(self, domain: DomainType) -> List[WorkedExample]:
        """Get all examples for a domain."""
        return self._by_domain.get(domain, [])

    def get_random(self, domain: DomainType) -> Optional[WorkedExample]:
        """Get a random example from a domain."""
        import random
        examples = self._by_domain.get(domain, [])
        return random.choice(examples) if examples else None

    def get_all(self) -> List[WorkedExample]:
        """Get all examples."""
        return list(self._examples.values())

    def count(self) -> int:
        """Total number of examples."""
        return len(self._examples)

    # =========================================================================
    # ARITHMETIC EXAMPLES (15)
    # =========================================================================

    def _arithmetic_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("arith_ex_001", DomainType.ARITHMETIC, "word_problem", "easy",
                "Janet's ducks lay 16 eggs per day. She eats 3 for breakfast and bakes 4 into muffins. How many eggs does she sell daily?",
                "Track total eggs and subtract consumption.",
                ["Eggs laid per day: 16", "Eggs eaten: 3", "Eggs baked: 4", "Total consumed: 3 + 4 = 7", "Eggs sold: 16 - 7 = 9"],
                "9 eggs", "GSM8K"),
            WorkedExample("arith_ex_002", DomainType.ARITHMETIC, "word_problem", "medium",
                "A farmer has 52 sheep. He buys 17 more, then sells 1/4 of his total flock. How many sheep remain?",
                "Calculate new total, then apply fraction.",
                ["Initial: 52 sheep", "After buying: 52 + 17 = 69", "Sold: 69 × 1/4 = 17.25 ≈ 17", "Remaining: 69 - 17 = 52"],
                "52 sheep", "GSM8K"),
            WorkedExample("arith_ex_003", DomainType.ARITHMETIC, "percentage", "medium",
                "A shirt costs $40. It's on sale for 25% off. What is the sale price?",
                "Calculate discount and subtract from original.",
                ["Original price: $40", "Discount: 40 × 0.25 = $10", "Sale price: 40 - 10 = $30"],
                "$30", "GSM8K"),
            WorkedExample("arith_ex_004", DomainType.ARITHMETIC, "multi_step", "hard",
                "Tom works 8 hours/day for $12/hour. He works 5 days/week. After 3 weeks, he spends half on rent. How much remains?",
                "Calculate total earnings, then spending.",
                ["Daily: 8 × 12 = $96", "Weekly: 96 × 5 = $480", "3 weeks: 480 × 3 = $1440", "After rent: 1440 ÷ 2 = $720"],
                "$720", "GSM8K"),
            WorkedExample("arith_ex_005", DomainType.ARITHMETIC, "fractions", "medium",
                "A pizza is cut into 8 slices. John eats 3/8 and Mary eats 1/4. What fraction is left?",
                "Find common denominator and subtract.",
                ["John: 3/8", "Mary: 1/4 = 2/8", "Eaten: 3/8 + 2/8 = 5/8", "Remaining: 8/8 - 5/8 = 3/8"],
                "3/8 of the pizza", "GSM8K"),
            WorkedExample("arith_ex_006", DomainType.ARITHMETIC, "ratio", "medium",
                "The ratio of boys to girls is 3:5. If there are 24 students total, how many are girls?",
                "Use ratio to find parts.",
                ["Total parts: 3 + 5 = 8", "Each part: 24 ÷ 8 = 3 students", "Girls: 5 × 3 = 15"],
                "15 girls", "GSM8K"),
            WorkedExample("arith_ex_007", DomainType.ARITHMETIC, "time", "medium",
                "A train leaves at 9:45 AM and arrives at 2:15 PM. How long is the journey?",
                "Calculate time difference.",
                ["From 9:45 to 12:00: 2 hours 15 min", "From 12:00 to 2:15: 2 hours 15 min", "Total: 4 hours 30 min"],
                "4 hours 30 minutes", "GSM8K"),
            WorkedExample("arith_ex_008", DomainType.ARITHMETIC, "compound", "hard",
                "Sarah invests $1000 at 5% annual interest, compounded yearly. What's the value after 2 years?",
                "Apply compound interest formula.",
                ["Year 1: 1000 × 1.05 = $1050", "Year 2: 1050 × 1.05 = $1102.50"],
                "$1102.50", "MATH"),
            WorkedExample("arith_ex_009", DomainType.ARITHMETIC, "average", "easy",
                "Find the average of 12, 18, 22, and 28.",
                "Sum and divide by count.",
                ["Sum: 12 + 18 + 22 + 28 = 80", "Count: 4", "Average: 80 ÷ 4 = 20"],
                "20", "GSM8K"),
            WorkedExample("arith_ex_010", DomainType.ARITHMETIC, "distance", "medium",
                "A car travels at 60 mph for 2.5 hours. How far does it go?",
                "Use distance = speed × time.",
                ["Speed: 60 mph", "Time: 2.5 hours", "Distance: 60 × 2.5 = 150 miles"],
                "150 miles", "GSM8K"),
            WorkedExample("arith_ex_011", DomainType.ARITHMETIC, "comparison", "easy",
                "Is 3/4 greater than 2/3?",
                "Find common denominator and compare.",
                ["3/4 = 9/12", "2/3 = 8/12", "9 > 8, so 3/4 > 2/3"],
                "Yes, 3/4 is greater", "MATH"),
            WorkedExample("arith_ex_012", DomainType.ARITHMETIC, "unit_conversion", "medium",
                "Convert 5 kilometers to meters.",
                "Use conversion factor: 1 km = 1000 m.",
                ["5 km × 1000 m/km = 5000 m"],
                "5000 meters", "GSM8K"),
            WorkedExample("arith_ex_013", DomainType.ARITHMETIC, "area", "medium",
                "Find the area of a rectangle with length 8 cm and width 5 cm.",
                "Use area = length × width.",
                ["Length: 8 cm", "Width: 5 cm", "Area: 8 × 5 = 40 sq cm"],
                "40 square centimeters", "MATH"),
            WorkedExample("arith_ex_014", DomainType.ARITHMETIC, "probability", "medium",
                "A bag has 3 red and 7 blue marbles. What's the probability of picking red?",
                "Probability = favorable / total.",
                ["Red: 3", "Total: 3 + 7 = 10", "P(red): 3/10 = 0.3"],
                "3/10 or 30%", "MATH"),
            WorkedExample("arith_ex_015", DomainType.ARITHMETIC, "mental_math", "hard",
                "Calculate 47 × 53 mentally.",
                "Use (50-3)(50+3) = 50² - 3².",
                ["Recognize as (50-3)(50+3)", "= 2500 - 9", "= 2491"],
                "2491", "MATH"),
        ]

    # =========================================================================
    # ALGORITHMIC EXAMPLES (15)
    # =========================================================================

    def _algorithmic_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("algo_ex_001", DomainType.ALGORITHMIC, "decomposition", "easy",
                "Plan the steps to make a peanut butter and jelly sandwich.",
                "Break into sequential steps.",
                ["Get bread, PB, jelly, knife", "Lay out two slices of bread", "Spread PB on one slice", "Spread jelly on other", "Press slices together"],
                "5-step sandwich making process", "BIG-Bench"),
            WorkedExample("algo_ex_002", DomainType.ALGORITHMIC, "sequencing", "medium",
                "Arrange these steps for doing laundry: Fold clothes, Add detergent, Dry clothes, Load washer, Sort clothes, Run wash cycle.",
                "Order by dependencies.",
                ["Sort clothes (must be first)", "Load washer", "Add detergent", "Run wash cycle", "Dry clothes", "Fold clothes (must be last)"],
                "Sort → Load → Detergent → Wash → Dry → Fold", "BIG-Bench"),
            WorkedExample("algo_ex_003", DomainType.ALGORITHMIC, "conditional", "medium",
                "If it's raining, take umbrella. If temperature < 50°F, wear coat. If both, do both. It's 45°F and raining. What do you do?",
                "Evaluate each condition.",
                ["Check rain: True → take umbrella", "Check temp: 45 < 50 → wear coat", "Both conditions met"],
                "Take umbrella AND wear coat", "BIG-Bench"),
            WorkedExample("algo_ex_004", DomainType.ALGORITHMIC, "loop", "medium",
                "What is the output? x = 0; for i in [1,2,3,4,5]: x = x + i",
                "Trace through iterations.",
                ["i=1: x = 0+1 = 1", "i=2: x = 1+2 = 3", "i=3: x = 3+3 = 6", "i=4: x = 6+4 = 10", "i=5: x = 10+5 = 15"],
                "15", "BIG-Bench"),
            WorkedExample("algo_ex_005", DomainType.ALGORITHMIC, "optimization", "hard",
                "You have 3 tasks taking 2h, 3h, 1h. Order to minimize average wait time?",
                "Shortest job first.",
                ["Sort by duration: 1h, 2h, 3h", "Wait times: 0, 1, 3 hours", "Average: (0+1+3)/3 = 1.33h"],
                "Order: 1h → 2h → 3h (avg wait 1.33h)", "BIG-Bench"),
            WorkedExample("algo_ex_006", DomainType.ALGORITHMIC, "recursion", "hard",
                "Calculate factorial of 5 using recursion.",
                "Base case and recursive step.",
                ["5! = 5 × 4!", "4! = 4 × 3!", "3! = 3 × 2!", "2! = 2 × 1!", "1! = 1 (base case)", "Unwind: 2×1=2, 6, 24, 120"],
                "120", "BIG-Bench"),
            WorkedExample("algo_ex_007", DomainType.ALGORITHMIC, "dependency", "medium",
                "Tasks: A (no deps), B (needs A), C (needs A), D (needs B,C). In what order?",
                "Topological sort.",
                ["A has no deps → do first", "B and C both depend on A → do after A (in any order)", "D depends on B,C → do last"],
                "A → B,C (either order) → D", "BIG-Bench"),
            WorkedExample("algo_ex_008", DomainType.ALGORITHMIC, "search", "medium",
                "Find 23 in sorted list [5,10,15,20,23,30,40] using binary search.",
                "Divide and conquer.",
                ["Mid: 20, 23>20 → search right half", "Right: [23,30,40], mid: 30, 23<30 → search left", "Left: [23], found!"],
                "Found at index 4", "BIG-Bench"),
            WorkedExample("algo_ex_009", DomainType.ALGORITHMIC, "state_machine", "hard",
                "Traffic light cycles: Green(30s) → Yellow(5s) → Red(30s) → Green. What's the state after 70 seconds?",
                "Track state transitions.",
                ["0-30s: Green", "30-35s: Yellow", "35-65s: Red", "65-95s: Green", "At 70s: Green"],
                "Green", "BIG-Bench"),
            WorkedExample("algo_ex_010", DomainType.ALGORITHMIC, "greedy", "medium",
                "Make change for 67 cents using fewest coins (quarters, dimes, nickels, pennies).",
                "Greedy: largest coins first.",
                ["67 ÷ 25 = 2 quarters (50¢), remainder 17¢", "17 ÷ 10 = 1 dime (10¢), remainder 7¢", "7 ÷ 5 = 1 nickel (5¢), remainder 2¢", "2 pennies"],
                "2 quarters, 1 dime, 1 nickel, 2 pennies = 6 coins", "BIG-Bench"),
            WorkedExample("algo_ex_011", DomainType.ALGORITHMIC, "backtracking", "hard",
                "Place 4 queens on 4×4 board so none attack each other. Is it possible?",
                "Try positions, backtrack on conflict.",
                ["Row 1: place at col 2", "Row 2: col 4 works", "Row 3: col 1 works", "Row 4: col 3 works"],
                "Yes: columns (2,4,1,3)", "BIG-Bench"),
            WorkedExample("algo_ex_012", DomainType.ALGORITHMIC, "scheduling", "medium",
                "3 people need printer: A(5min), B(2min), C(3min). One printer. Minimize total wait.",
                "Shortest job first.",
                ["Order: B(2), C(3), A(5)", "B waits 0, C waits 2, A waits 5", "Total: 0+2+5 = 7 min"],
                "Order B→C→A, total wait 7 minutes", "BIG-Bench"),
            WorkedExample("algo_ex_013", DomainType.ALGORITHMIC, "divide_conquer", "hard",
                "Find maximum in [3,7,2,9,1,5] using divide and conquer.",
                "Split, solve subproblems, combine.",
                ["Split: [3,7,2] and [9,1,5]", "Left max: 7", "Right max: 9", "Overall max: max(7,9) = 9"],
                "9", "BIG-Bench"),
            WorkedExample("algo_ex_014", DomainType.ALGORITHMIC, "invariant", "hard",
                "Loop: x=10, y=0. While x>0: x=x-1, y=y+1. What's invariant?",
                "Find property true each iteration.",
                ["Start: x+y = 10+0 = 10", "After 1: x+y = 9+1 = 10", "After 2: x+y = 8+2 = 10", "Invariant: x+y = 10 always"],
                "x + y = 10", "BIG-Bench"),
            WorkedExample("algo_ex_015", DomainType.ALGORITHMIC, "simulation", "medium",
                "Simulate: start at 0, flip coin 3 times. Heads +1, Tails -1. Possible end positions?",
                "Enumerate all paths.",
                ["HHH: 0+1+1+1 = 3", "HHT: 0+1+1-1 = 1", "HTH: 1, HTT: -1", "THH: 1, THT: -1, TTH: -1, TTT: -3"],
                "Possible: -3, -1, 1, 3", "BIG-Bench"),
        ]

    # =========================================================================
    # FACTUAL EXAMPLES (15)
    # =========================================================================

    def _factual_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("fact_ex_001", DomainType.FACTUAL, "history", "easy",
                "In what year did World War II end?",
                "Direct recall of historical date.",
                ["WWII ended in 1945", "Germany surrendered May 1945", "Japan surrendered August 1945"],
                "1945", "TriviaQA"),
            WorkedExample("fact_ex_002", DomainType.FACTUAL, "geography", "easy",
                "What is the capital of France?",
                "Direct recall of capital city.",
                ["France is a country in Western Europe", "Its capital is Paris"],
                "Paris", "TriviaQA"),
            WorkedExample("fact_ex_003", DomainType.FACTUAL, "science", "medium",
                "What is the chemical symbol for gold?",
                "Recall periodic table element.",
                ["Gold is a precious metal", "Its Latin name is 'Aurum'", "Symbol derived from Latin: Au"],
                "Au", "MMLU"),
            WorkedExample("fact_ex_004", DomainType.FACTUAL, "culture", "medium",
                "Who painted the Mona Lisa?",
                "Recall famous artwork creator.",
                ["Mona Lisa is a famous painting", "Created during the Renaissance", "Painted by Leonardo da Vinci"],
                "Leonardo da Vinci", "TriviaQA"),
            WorkedExample("fact_ex_005", DomainType.FACTUAL, "history", "medium",
                "Who was the first President of the United States?",
                "Recall founding figure.",
                ["US declared independence in 1776", "Constitution ratified 1788", "First president elected: George Washington"],
                "George Washington", "TriviaQA"),
            WorkedExample("fact_ex_006", DomainType.FACTUAL, "geography", "medium",
                "What is the largest ocean on Earth?",
                "Recall geographic fact.",
                ["Earth has five major oceans", "Pacific, Atlantic, Indian, Southern, Arctic", "Pacific is largest"],
                "Pacific Ocean", "TriviaQA"),
            WorkedExample("fact_ex_007", DomainType.FACTUAL, "science", "medium",
                "How many planets are in our solar system?",
                "Recall astronomical fact.",
                ["Mercury, Venus, Earth, Mars", "Jupiter, Saturn, Uranus, Neptune", "Pluto reclassified as dwarf planet in 2006"],
                "8 planets", "MMLU"),
            WorkedExample("fact_ex_008", DomainType.FACTUAL, "culture", "hard",
                "In what year was the first iPhone released?",
                "Recall technology history.",
                ["Apple announced iPhone in January 2007", "Steve Jobs unveiled it at Macworld", "Released June 29, 2007"],
                "2007", "TriviaQA"),
            WorkedExample("fact_ex_009", DomainType.FACTUAL, "history", "hard",
                "What empire built the Colosseum in Rome?",
                "Recall ancient history.",
                ["Colosseum built in 70-80 AD", "During reign of Vespasian and Titus", "Roman Empire"],
                "Roman Empire", "TriviaQA"),
            WorkedExample("fact_ex_010", DomainType.FACTUAL, "science", "easy",
                "What gas do plants absorb for photosynthesis?",
                "Recall biology fact.",
                ["Photosynthesis converts light to energy", "Plants use CO2 and water", "Produce oxygen and glucose"],
                "Carbon dioxide (CO2)", "MMLU"),
            WorkedExample("fact_ex_011", DomainType.FACTUAL, "geography", "hard",
                "What is the longest river in the world?",
                "Recall geographic fact.",
                ["Debate between Nile and Amazon", "Nile traditionally considered longest at ~6,650 km", "Amazon may be longer by some measurements"],
                "Nile River (or Amazon, depending on measurement)", "TriviaQA"),
            WorkedExample("fact_ex_012", DomainType.FACTUAL, "culture", "medium",
                "Who wrote 'Romeo and Juliet'?",
                "Recall literary author.",
                ["Famous tragedy about star-crossed lovers", "Written during English Renaissance", "By William Shakespeare"],
                "William Shakespeare", "TriviaQA"),
            WorkedExample("fact_ex_013", DomainType.FACTUAL, "science", "hard",
                "What is the speed of light in a vacuum?",
                "Recall physics constant.",
                ["Fundamental constant in physics", "Denoted by 'c'", "Approximately 299,792,458 m/s"],
                "~300,000 km/s or 299,792,458 m/s", "MMLU"),
            WorkedExample("fact_ex_014", DomainType.FACTUAL, "history", "medium",
                "What wall fell in 1989, symbolizing the end of the Cold War?",
                "Recall modern history.",
                ["Cold War divided Europe", "Berlin divided into East and West", "Berlin Wall fell November 9, 1989"],
                "Berlin Wall", "TriviaQA"),
            WorkedExample("fact_ex_015", DomainType.FACTUAL, "geography", "medium",
                "What country has the largest population?",
                "Recall demographic fact.",
                ["As of 2023-2024, India surpassed China", "Both have over 1.4 billion people", "India now has slight lead"],
                "India (as of 2023)", "TriviaQA"),
        ]

    # Remaining domains follow same pattern...

    def _procedural_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("proc_ex_001", DomainType.PROCEDURAL, "cooking", "easy",
                "How do you boil an egg?",
                "Step-by-step cooking procedure.",
                ["Place egg in pot", "Cover with cold water", "Bring to boil", "Turn off heat, cover 10-12 min", "Transfer to ice bath"],
                "Boiled egg ready in ~15 minutes", "wikiHow"),
            WorkedExample("proc_ex_002", DomainType.PROCEDURAL, "technology", "medium",
                "How do you reset a router?",
                "Technology troubleshooting procedure.",
                ["Locate reset button (usually small hole)", "Press and hold for 10-30 seconds", "Wait for router to restart", "Reconfigure settings"],
                "Router reset to factory defaults", "wikiHow"),
            WorkedExample("proc_ex_003", DomainType.PROCEDURAL, "first_aid", "medium",
                "How do you treat a minor burn?",
                "Medical procedure for minor injury.",
                ["Cool burn under running water 10-20 min", "Do NOT use ice", "Apply aloe or burn cream", "Cover with loose bandage", "Seek help if severe"],
                "Burn treated and protected", "wikiHow"),
            WorkedExample("proc_ex_004", DomainType.PROCEDURAL, "maintenance", "medium",
                "How do you change a car tire?",
                "Vehicle maintenance procedure.",
                ["Pull over safely, engage parking brake", "Loosen lug nuts before jacking", "Position jack and raise car", "Remove lug nuts and tire", "Install spare, hand-tighten", "Lower car, fully tighten lug nuts"],
                "Spare tire installed safely", "wikiHow"),
            WorkedExample("proc_ex_005", DomainType.PROCEDURAL, "gardening", "easy",
                "How do you plant a seed?",
                "Basic gardening procedure.",
                ["Fill pot with soil", "Make hole 2-3x seed size", "Place seed in hole", "Cover lightly with soil", "Water gently", "Place in sunny spot"],
                "Seed planted and ready to grow", "wikiHow"),
            WorkedExample("proc_ex_006", DomainType.PROCEDURAL, "finance", "medium",
                "How do you create a budget?",
                "Financial planning procedure.",
                ["List all income sources", "Track all expenses for a month", "Categorize expenses", "Set spending limits per category", "Review and adjust monthly"],
                "Monthly budget established", "wikiHow"),
            WorkedExample("proc_ex_007", DomainType.PROCEDURAL, "cleaning", "easy",
                "How do you clean a coffee maker?",
                "Appliance maintenance.",
                ["Mix equal parts water and white vinegar", "Pour into reservoir", "Run half cycle, pause 30 min", "Complete cycle", "Run 2-3 cycles with plain water"],
                "Coffee maker descaled and clean", "wikiHow"),
            WorkedExample("proc_ex_008", DomainType.PROCEDURAL, "technology", "hard",
                "How do you set up two-factor authentication?",
                "Security procedure.",
                ["Go to account security settings", "Select 2FA option", "Choose method (app, SMS, key)", "Follow setup prompts", "Save backup codes securely", "Test login with 2FA"],
                "Account protected with 2FA", "wikiHow"),
            WorkedExample("proc_ex_009", DomainType.PROCEDURAL, "crafts", "medium",
                "How do you fold an origami crane?",
                "Paper folding procedure.",
                ["Start with square paper", "Fold into triangle, then square base", "Create petal fold on both sides", "Fold wings down", "Fold head and tail", "Shape body"],
                "Completed origami crane", "wikiHow"),
            WorkedExample("proc_ex_010", DomainType.PROCEDURAL, "exercise", "easy",
                "How do you do a proper push-up?",
                "Exercise form procedure.",
                ["Start in plank position", "Hands slightly wider than shoulders", "Lower body until chest near floor", "Keep core tight, body straight", "Push back up to start"],
                "One proper push-up completed", "wikiHow"),
            WorkedExample("proc_ex_011", DomainType.PROCEDURAL, "cooking", "medium",
                "How do you make pasta from scratch?",
                "Advanced cooking procedure.",
                ["Mix 2 cups flour, 3 eggs", "Knead 10 minutes until smooth", "Rest dough 30 min", "Roll thin with pasta machine", "Cut to desired shape", "Cook in salted boiling water 2-3 min"],
                "Fresh pasta ready to serve", "wikiHow"),
            WorkedExample("proc_ex_012", DomainType.PROCEDURAL, "photography", "medium",
                "How do you take a good portrait photo?",
                "Photography technique.",
                ["Use natural light from window", "Position subject at 45° angle", "Focus on eyes", "Use wide aperture for blur", "Leave space in direction of gaze"],
                "Flattering portrait captured", "wikiHow"),
            WorkedExample("proc_ex_013", DomainType.PROCEDURAL, "organization", "easy",
                "How do you organize a closet?",
                "Home organization procedure.",
                ["Empty entire closet", "Sort: keep, donate, discard", "Clean closet surfaces", "Group similar items", "Use uniform hangers", "Store rarely-used items high"],
                "Organized, accessible closet", "wikiHow"),
            WorkedExample("proc_ex_014", DomainType.PROCEDURAL, "pets", "medium",
                "How do you give a dog a bath?",
                "Pet care procedure.",
                ["Brush out tangles first", "Use lukewarm water", "Wet thoroughly, avoiding ears", "Apply dog shampoo, massage in", "Rinse completely", "Dry with towel, then dryer on low"],
                "Clean, dry dog", "wikiHow"),
            WorkedExample("proc_ex_015", DomainType.PROCEDURAL, "emergency", "hard",
                "How do you perform CPR on an adult?",
                "Emergency medical procedure.",
                ["Call 911 first", "Place heel of hand on center of chest", "Interlock fingers, arms straight", "Compress 2 inches deep, 100-120/min", "After 30 compressions, give 2 breaths", "Continue until help arrives"],
                "CPR performed until EMS arrives", "wikiHow"),
        ]

    def _creative_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("creat_ex_001", DomainType.CREATIVE, "short_story", "easy",
                "Write a 50-word story about finding a key.",
                "Use compact narrative structure.",
                ["Establish character quickly", "Introduce key as mystery", "Create tension", "Resolve with meaning"],
                "The rusty key had waited in the garden soil for sixty years. Maria's fingers trembled as she recognized her grandmother's initials. She ran to the attic, to the locked chest she'd wondered about since childhood. Inside: letters, photos, and a truth that changed everything.", "WritingPrompts"),
            WorkedExample("creat_ex_002", DomainType.CREATIVE, "poetry", "medium",
                "Write a haiku about autumn.",
                "Follow 5-7-5 syllable structure.",
                ["Line 1: 5 syllables", "Line 2: 7 syllables", "Line 3: 5 syllables", "Capture seasonal essence"],
                "Crimson leaves descend / Whispering secrets to earth / Winter's breath draws near", "WritingPrompts"),
            WorkedExample("creat_ex_003", DomainType.CREATIVE, "dialogue", "medium",
                "Write a tense conversation between two people who haven't spoken in years.",
                "Reveal relationship through subtext.",
                ["Show awkwardness in short sentences", "Use what's unsaid as much as said", "Build to emotional moment"],
                "'You look well.' 'You don't.' She set down her coffee. 'That's not—' 'I know what you meant.' Silence stretched between them like the years had. 'I'm sorry,' he finally said. 'I know,' she replied. 'But knowing doesn't fix it.'", "WritingPrompts"),
            WorkedExample("creat_ex_004", DomainType.CREATIVE, "description", "medium",
                "Describe a thunderstorm using all five senses.",
                "Engage each sense vividly.",
                ["Sight: lightning, dark clouds", "Sound: thunder, rain", "Smell: petrichor, ozone", "Touch: humidity, rain", "Taste: electric air"],
                "Lightning fractured the purple sky, followed by thunder that vibrated through my chest. The air hung thick and electric, tasting of copper on my tongue. Petrichor rose from the parched earth as fat raindrops pounded the roof, and cool mist kissed my upturned face.", "WritingPrompts"),
            WorkedExample("creat_ex_005", DomainType.CREATIVE, "narrative", "hard",
                "Write a story where the first and last sentences are the same, but mean different things.",
                "Use context to change meaning.",
                ["Write sentence with multiple meanings", "Build narrative that shifts meaning", "Return to sentence with new context"],
                "'I never knew my father.' These words began my search—through records, photos, strangers' memories. And when I finally found him in the nursing home, Alzheimer's having stolen his mind, I held his hand and whispered the only truth left: 'I never knew my father.'", "WritingPrompts"),
            WorkedExample("creat_ex_006", DomainType.CREATIVE, "character", "medium",
                "Introduce a villain without stating they're a villain.",
                "Show character through actions and details.",
                ["Use subtle red flags", "Let reader infer morality", "Avoid explicit judgment"],
                "Margaret always remembered everyone's birthday. She'd arrive with perfect gifts, a warm smile, questions about your children's names. 'You're so thoughtful,' people said. They didn't see her notebook, the careful records, the way information flowed to her like rivers to the sea.", "WritingPrompts"),
            WorkedExample("creat_ex_007", DomainType.CREATIVE, "micro_fiction", "hard",
                "Tell a complete story in exactly six words.",
                "Maximum compression, full narrative arc.",
                ["Imply beginning, middle, end", "Use every word precisely", "Leave space for reader"],
                "Strangers. Friends. Lovers. Strangers again. Closure.", "WritingPrompts"),
            WorkedExample("creat_ex_008", DomainType.CREATIVE, "poetry", "hard",
                "Write a sonnet about technology.",
                "14 lines, iambic pentameter, rhyme scheme.",
                ["Follow ABAB CDCD EFEF GG", "10 syllables per line", "Turn at line 9", "Conclude in couplet"],
                "Upon my desk a glowing portal waits, / Connecting me to worlds I'll never see. / Through fiber veins, the data permeates / A web of ones and zeros, binding me...", "WritingPrompts"),
            WorkedExample("creat_ex_009", DomainType.CREATIVE, "scene", "medium",
                "Write a scene that takes place entirely in an elevator.",
                "Use confined space for tension.",
                ["Limited setting, high stakes", "Use time pressure", "Reveal through dialogue"],
                "Twenty floors. That's all she had. 'I know what you did,' she said to his reflection in the steel doors. His finger hovered over the emergency stop. 'You can't prove anything.' 'I don't need to.' She held up her phone, recording.", "WritingPrompts"),
            WorkedExample("creat_ex_010", DomainType.CREATIVE, "rewrite", "medium",
                "Retell 'Three Little Pigs' from the wolf's perspective.",
                "Shift perspective to create new meaning.",
                ["Humanize the antagonist", "Provide motivation", "Same events, different interpretation"],
                "I just wanted sugar for my grandmother's birthday cake. That's all. But try asking pigs for anything. The first two were rude—their houses practically fell apart when I knocked! The third one tried to BOIL me. Who's the real villain here?", "WritingPrompts"),
            WorkedExample("creat_ex_011", DomainType.CREATIVE, "worldbuilding", "hard",
                "In one paragraph, establish a fantasy world's rules.",
                "Efficient exposition through implication.",
                ["Show rules through action", "Imply history", "Create sense of depth"],
                "Kira traced the glyph carefully—three drops of blood for fire, one for each year she'd studied. The Academy masters said talent was inherited, which explained why orphans like her had to pay in pain. Outside, the noble-born flew past on their effortless flames.", "WritingPrompts"),
            WorkedExample("creat_ex_012", DomainType.CREATIVE, "twist", "hard",
                "Write a story with a twist that recontextualizes everything.",
                "Plant clues that reveal on second reading.",
                ["Establish normal situation", "Drop subtle hints", "Reveal that changes meaning"],
                "Mom always said I was special, that I could see things others couldn't. The children at the park never talked to me, but I was used to being shy. Today Mom brought flowers to a stone with my name on it. That's when I understood why I was special.", "WritingPrompts"),
            WorkedExample("creat_ex_013", DomainType.CREATIVE, "mood", "medium",
                "Write the same scene twice: once hopeful, once ominous.",
                "Show how word choice affects tone.",
                ["Same facts, different connotation", "Positive vs negative word choice", "Demonstrate author's power"],
                "HOPEFUL: Morning light spilled through the window as she packed her last box. A new city, a fresh start, a chance to become whoever she wanted. OMINOUS: Gray light seeped through the window as she packed her last box. A strange city, an unknown future, no one who knew her name.", "WritingPrompts"),
            WorkedExample("creat_ex_014", DomainType.CREATIVE, "voice", "medium",
                "Write the same event from a child's and adult's perspective.",
                "Voice reflects character.",
                ["Child: simple words, wonder", "Adult: complex, nuanced", "Same event, different meaning"],
                "CHILD (age 6): Daddy went to sleep forever and everyone is sad and wearing black. Grammy says he's watching from heaven but I don't see him when I look up. ADULT: The eulogy I'd prepared died in my throat. How do you summarize a father in five minutes?", "WritingPrompts"),
            WorkedExample("creat_ex_015", DomainType.CREATIVE, "genre_blend", "hard",
                "Write a romance scene in the style of a nature documentary.",
                "Blend genres for comedic/fresh effect.",
                ["Use documentary voice", "Describe human behavior as animal", "Maintain narrative"],
                "Here we observe the male approaching the female's territory—a coffee shop. Note the careful grooming, the rehearsed greeting discarded at the last moment. 'Hi, um, is this seat taken?' Fascinating. The female's micro-expressions suggest interest. The mating dance has begun.", "WritingPrompts"),
        ]

    def _summarization_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("summ_ex_001", DomainType.SUMMARIZATION, "news", "easy",
                "Summarize: 'Apple Inc. announced today it will release the iPhone 15 in September. The new device features a titanium design, improved camera, and USB-C port. Pre-orders begin September 15. Starting price is $799.'",
                "Extract key facts.",
                ["Who: Apple", "What: iPhone 15 launch", "When: September, pre-orders Sep 15", "Price: $799"],
                "Apple will release iPhone 15 in September with titanium design, better camera, and USB-C. Pre-orders Sep 15, starting at $799.", "CNN"),
            WorkedExample("summ_ex_002", DomainType.SUMMARIZATION, "academic", "medium",
                "Summarize this abstract about climate change effects on coral reefs...",
                "Capture methodology and findings.",
                ["State research question", "Note methods briefly", "Summarize key findings", "State implications"],
                "Study examined 50 reef sites over 10 years, finding 30% coral decline correlated with temperature rises above 1.5°C. Recommends urgent emission reductions.", "BIG-Bench"),
            WorkedExample("summ_ex_003", DomainType.SUMMARIZATION, "meeting", "medium",
                "Summarize meeting notes covering Q3 sales, new hire onboarding, and office relocation.",
                "Extract action items and decisions.",
                ["List main topics", "Note decisions made", "Capture action items", "Include deadlines"],
                "Q3 sales exceeded targets by 15%. Three new hires start Monday. Office move confirmed for Nov 1. ACTION: All hands meeting scheduled Oct 15.", "BIG-Bench"),
            WorkedExample("summ_ex_004", DomainType.SUMMARIZATION, "book", "hard",
                "Write a one-paragraph summary of '1984' by George Orwell.",
                "Capture theme and plot essence.",
                ["Introduce setting", "Main character and conflict", "Key themes", "Avoid spoilers or include ending note"],
                "Orwell's dystopian novel follows Winston Smith in Oceania, a totalitarian state where the Party controls all aspects of life. Winston's forbidden love affair and secret rebellion against Big Brother lead to his capture and psychological destruction, illustrating how absolute power corrupts absolutely.", "BIG-Bench"),
            WorkedExample("summ_ex_005", DomainType.SUMMARIZATION, "legal", "hard",
                "Summarize this contract clause about termination...",
                "Preserve legal precision.",
                ["Identify parties' rights", "Note conditions", "State consequences", "Keep critical terms"],
                "Either party may terminate with 30 days written notice. Immediate termination permitted for material breach. Upon termination, all confidential materials must be returned within 5 business days.", "BIG-Bench"),
            WorkedExample("summ_ex_006", DomainType.SUMMARIZATION, "technical", "medium",
                "Summarize how blockchain consensus works...",
                "Simplify technical content.",
                ["Identify core concept", "Explain mechanism simply", "Note key benefit"],
                "Blockchain uses consensus mechanisms where network participants validate transactions before adding them to the permanent record. This distributed verification eliminates need for central authority while ensuring data integrity.", "BIG-Bench"),
            WorkedExample("summ_ex_007", DomainType.SUMMARIZATION, "email", "easy",
                "Summarize this long email thread about project deadline extension request.",
                "Extract request and response.",
                ["Identify requester", "Note request", "Capture decision"],
                "Team lead requested 2-week extension due to unexpected technical issues. Manager approved with condition that weekly progress reports be submitted.", "BIG-Bench"),
            WorkedExample("summ_ex_008", DomainType.SUMMARIZATION, "research", "hard",
                "Summarize a 10-page research paper on machine learning fairness.",
                "Capture contribution and findings.",
                ["State problem addressed", "Note methodology", "Summarize results", "State significance"],
                "Paper introduces bias detection framework for ML models. Tests on 5 datasets show method identifies 89% of discriminatory patterns. Proposes mitigation strategies reducing bias by 40% with minimal accuracy loss.", "BIG-Bench"),
            WorkedExample("summ_ex_009", DomainType.SUMMARIZATION, "speech", "medium",
                "Summarize the key points of MLK's 'I Have a Dream' speech.",
                "Capture theme and rhetoric.",
                ["Main message", "Key imagery", "Call to action"],
                "King's 1963 speech at the March on Washington envisioned racial equality in America. Using powerful metaphors of promissory notes and dreams, he called for nonviolent resistance and judging people by character rather than color.", "BIG-Bench"),
            WorkedExample("summ_ex_010", DomainType.SUMMARIZATION, "movie", "easy",
                "Summarize the plot of 'The Matrix' in 3 sentences.",
                "Capture main arc without spoilers.",
                ["Setup", "Conflict", "Resolution hint"],
                "A computer hacker discovers reality is a simulation created by machines to control humanity. Recruited by rebels, he learns he may be 'The One' prophesied to end the war. He must choose between comfortable illusion and dangerous truth.", "BIG-Bench"),
            WorkedExample("summ_ex_011", DomainType.SUMMARIZATION, "podcast", "medium",
                "Summarize an hour-long podcast interview with a startup founder.",
                "Extract key insights and stories.",
                ["Guest background", "Main topics covered", "Key takeaways"],
                "Interview with Jane Doe, founder of TechStartup (sold for $50M). Discussed failed first startup, pivot that led to success, and importance of customer feedback. Key advice: 'Ship fast, learn faster.'", "BIG-Bench"),
            WorkedExample("summ_ex_012", DomainType.SUMMARIZATION, "report", "hard",
                "Summarize a quarterly financial report.",
                "Capture key metrics and outlook.",
                ["Revenue/profit figures", "YoY comparison", "Future guidance"],
                "Q3 revenue $2.4B (+12% YoY), net income $340M. Growth driven by cloud services (+28%). Full-year guidance raised to $9.5B revenue. Concerns: supply chain costs up 8%.", "BIG-Bench"),
            WorkedExample("summ_ex_013", DomainType.SUMMARIZATION, "instructions", "easy",
                "Summarize a 500-word product assembly manual.",
                "Reduce to essential steps.",
                ["List required tools", "Summarize major steps", "Note warnings"],
                "Assembly requires Phillips screwdriver. 1) Attach base to frame (4 screws). 2) Install shelves bottom to top. 3) Secure back panel. 4) Attach doors. WARNING: Two-person job for step 2.", "BIG-Bench"),
            WorkedExample("summ_ex_014", DomainType.SUMMARIZATION, "story", "medium",
                "Summarize 'The Gift of the Magi' by O. Henry.",
                "Capture plot and theme.",
                ["Setup", "Both sacrifices", "Irony and meaning"],
                "A poor couple each secretly sells their most prized possession to buy a gift for the other. She sells her hair for a watch chain; he sells his watch for combs. The ironic twist reveals their selfless love is the true gift.", "BIG-Bench"),
            WorkedExample("summ_ex_015", DomainType.SUMMARIZATION, "debate", "hard",
                "Summarize both sides of a debate on universal basic income.",
                "Present balanced summary.",
                ["Pro arguments", "Con arguments", "Key point of contention"],
                "Proponents argue UBI eliminates poverty, simplifies welfare, and prepares for automation. Opponents cite high costs, inflation risks, and reduced work incentives. Central debate: whether benefits outweigh the $3T+ annual cost.", "BIG-Bench"),
        ]

    def _causal_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("caus_ex_001", DomainType.CAUSAL, "physical", "easy",
                "Why does ice float on water?",
                "Explain physical causation.",
                ["Water expands when frozen", "Ice is less dense than liquid water", "Less dense objects float"],
                "Ice floats because water expands when it freezes, making ice less dense than liquid water. Less dense substances float on more dense ones.", "BIG-Bench"),
            WorkedExample("caus_ex_002", DomainType.CAUSAL, "social", "medium",
                "Why did the Roman Empire fall?",
                "Analyze multiple causes.",
                ["List contributing factors", "Note interactions", "Identify key causes"],
                "Rome fell due to multiple interacting causes: military overextension, economic troubles, political instability, Germanic invasions, and declining civic virtue. No single cause—the combination created unsustainable pressures.", "BIG-Bench"),
            WorkedExample("caus_ex_003", DomainType.CAUSAL, "economic", "medium",
                "Why do prices rise during inflation?",
                "Explain economic mechanism.",
                ["Too much money chasing goods", "Supply/demand imbalance", "Self-reinforcing cycle"],
                "Inflation occurs when money supply grows faster than goods/services. More money chasing same goods drives prices up. This can become self-reinforcing as people buy now expecting higher future prices.", "BIG-Bench"),
            WorkedExample("caus_ex_004", DomainType.CAUSAL, "biological", "medium",
                "Why do people yawn when others yawn?",
                "Explain biological/social causation.",
                ["Mirror neurons", "Social bonding mechanism", "Evolutionary theory"],
                "Contagious yawning involves mirror neurons that activate when observing others' actions. This may have evolved for social bonding and group synchronization of alertness levels.", "BIG-Bench"),
            WorkedExample("caus_ex_005", DomainType.CAUSAL, "prediction", "medium",
                "If greenhouse gas emissions continue rising, what will happen to sea levels?",
                "Predict effect from cause.",
                ["Higher emissions → more warming", "Warming → ice melt + thermal expansion", "Result: rising seas"],
                "Continued emissions will cause further warming, melting polar ice and expanding ocean water. Sea levels could rise 1-3 feet by 2100, flooding coastal cities.", "BIG-Bench"),
            WorkedExample("caus_ex_006", DomainType.CAUSAL, "counterfactual", "hard",
                "What if the internet had never been invented?",
                "Reason about alternative history.",
                ["Consider direct effects", "Second-order effects", "What would substitute"],
                "Without internet: no email, e-commerce, social media, or smartphones as we know them. Information access would remain limited. Libraries and physical mail would remain central. Economic growth would be significantly slower.", "BIG-Bench"),
            WorkedExample("caus_ex_007", DomainType.CAUSAL, "chain", "medium",
                "Trace the causal chain: How does studying lead to good grades?",
                "Map complete causal path.",
                ["Study → understanding", "Understanding → test performance", "Performance → grades"],
                "Studying exposes you to material, creating mental models. These models enable correct answers on tests. Tests are scored, producing grades. The chain: Study → Encoding → Retrieval → Performance → Grade.", "BIG-Bench"),
            WorkedExample("caus_ex_008", DomainType.CAUSAL, "medical", "hard",
                "Why does lack of sleep affect cognitive function?",
                "Explain biological causation.",
                ["Sleep consolidates memory", "Sleep clears brain waste", "Deprivation impairs these"],
                "Sleep allows memory consolidation and clearing of metabolic waste from brain. Without sleep, memories don't form properly, waste accumulates, and neural pathways become less efficient, causing cognitive impairment.", "BIG-Bench"),
            WorkedExample("caus_ex_009", DomainType.CAUSAL, "diagnostic", "medium",
                "The plant is dying. Leaves are yellow with brown spots. What's the cause?",
                "Diagnose from symptoms.",
                ["Yellow leaves: nutrient or water issue", "Brown spots: disease or sunburn", "Combined: likely overwatering → root rot"],
                "Yellow leaves with brown spots often indicate overwatering causing root rot. Waterlogged roots can't absorb nutrients (yellowing) and develop fungal infections (spots). Solution: reduce watering, check drainage.", "BIG-Bench"),
            WorkedExample("caus_ex_010", DomainType.CAUSAL, "behavioral", "medium",
                "Why do people procrastinate even when they know the consequences?",
                "Explain psychological causation.",
                ["Immediate vs delayed reward", "Emotional regulation", "Present bias"],
                "Procrastination stems from prioritizing immediate comfort over future benefit (present bias). The brain weighs current emotional relief from avoidance higher than distant negative consequences.", "BIG-Bench"),
            WorkedExample("caus_ex_011", DomainType.CAUSAL, "environmental", "hard",
                "Why are coral reefs dying around the world?",
                "Analyze environmental causation.",
                ["Direct causes: heat, acid, pollution", "Root cause: human activity", "Feedback loops"],
                "Coral death results from ocean warming (bleaching), acidification (dissolving skeletons), and pollution (suffocation). Root cause: fossil fuel emissions. Feedback: dead reefs → less carbon absorption → more warming.", "BIG-Bench"),
            WorkedExample("caus_ex_012", DomainType.CAUSAL, "technological", "medium",
                "Why did smartphones replace landlines?",
                "Explain technological displacement.",
                ["Portability advantage", "Functionality expansion", "Network effects"],
                "Smartphones offered mobility plus growing functionality (internet, apps, camera). Network effects accelerated adoption as more users meant more app development. Landlines couldn't compete on convenience or capability.", "BIG-Bench"),
            WorkedExample("caus_ex_013", DomainType.CAUSAL, "prevention", "medium",
                "How can regular exercise prevent heart disease?",
                "Explain preventive mechanism.",
                ["Exercise strengthens heart", "Improves cholesterol", "Reduces inflammation"],
                "Exercise strengthens heart muscle, improves blood flow, raises HDL (good cholesterol), lowers blood pressure, and reduces inflammation—all risk factors for heart disease. Regular activity maintains these benefits.", "BIG-Bench"),
            WorkedExample("caus_ex_014", DomainType.CAUSAL, "unintended", "hard",
                "What were the unintended consequences of Prohibition?",
                "Analyze unexpected effects.",
                ["Intended effect vs actual", "Second-order effects", "Long-term consequences"],
                "Prohibition (1920-1933) intended to reduce alcohol harm but instead: created organized crime (bootlegging), increased dangerous drinking (unregulated alcohol), corrupted law enforcement, and lost tax revenue. A case study in policy unintended consequences.", "BIG-Bench"),
            WorkedExample("caus_ex_015", DomainType.CAUSAL, "mechanism", "hard",
                "Explain the mechanism by which vaccines create immunity.",
                "Detail biological process.",
                ["Antigen introduction", "Immune response", "Memory formation"],
                "Vaccines introduce weakened/inactive pathogens or their components. The immune system recognizes these antigens and produces antibodies. Memory cells remember the pathogen, enabling rapid response if exposed to the real disease.", "BIG-Bench"),
        ]

    def _analogical_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("anal_ex_001", DomainType.ANALOGICAL, "proportional", "easy",
                "Hand is to glove as foot is to ___?",
                "Identify body part to covering relationship.",
                ["Hand is covered by glove", "Foot is covered by..."],
                "Sock (or shoe)", "SAT Analogies"),
            WorkedExample("anal_ex_002", DomainType.ANALOGICAL, "proportional", "medium",
                "Painter is to brush as writer is to ___?",
                "Professional to tool relationship.",
                ["Painter uses brush to create", "Writer uses... to create"],
                "Pen (or keyboard)", "SAT Analogies"),
            WorkedExample("anal_ex_003", DomainType.ANALOGICAL, "proportional", "hard",
                "Symphony is to composer as novel is to ___?",
                "Artwork to creator relationship.",
                ["Symphony created by composer", "Novel created by..."],
                "Author", "SAT Analogies"),
            WorkedExample("anal_ex_004", DomainType.ANALOGICAL, "metaphor", "medium",
                "Explain: 'Time is money'",
                "Interpret conceptual metaphor.",
                ["Time is a resource", "Can be 'spent,' 'wasted,' 'saved'", "Both have value that can be lost"],
                "This metaphor frames time as a valuable, limited resource like money. Both can be spent wisely or wasted. The metaphor encourages treating time with the same care as financial resources.", "BIG-Bench"),
            WorkedExample("anal_ex_005", DomainType.ANALOGICAL, "metaphor", "hard",
                "Analyze: 'The brain is a computer'",
                "Evaluate metaphor limitations.",
                ["Similarities: processing, memory, inputs/outputs", "Differences: emotion, consciousness, learning", "Metaphor insight and limits"],
                "This metaphor highlights information processing similarities but obscures key differences. Brains are wet, emotional, embodied, and learn differently than silicon computers. Useful but incomplete model.", "BIG-Bench"),
            WorkedExample("anal_ex_006", DomainType.ANALOGICAL, "pattern", "medium",
                "2, 6, 12, 20, 30, ___?",
                "Find numerical pattern.",
                ["Differences: 4, 6, 8, 10, ...", "Pattern: differences increase by 2", "Next difference: 12"],
                "42 (30 + 12)", "ARC"),
            WorkedExample("anal_ex_007", DomainType.ANALOGICAL, "visual", "medium",
                "If △ → ▷ → ◇, then □ → ?",
                "Apply rotation transformation.",
                ["Triangle rotates 90° each step", "Square should rotate similarly"],
                "◇ (rotated 45°/diamond)", "ARC"),
            WorkedExample("anal_ex_008", DomainType.ANALOGICAL, "cross_domain", "hard",
                "How is a cell like a factory?",
                "Map structures between domains.",
                ["Nucleus = management/blueprints", "Mitochondria = power plant", "Ribosomes = assembly line", "Membrane = walls/security"],
                "Cell nucleus stores instructions like a factory office. Mitochondria generate power like a power plant. Ribosomes assemble proteins like an assembly line. The membrane controls what enters/exits like factory security.", "BIG-Bench"),
            WorkedExample("anal_ex_009", DomainType.ANALOGICAL, "cross_domain", "hard",
                "Apply the water cycle analogy to the economic cycle.",
                "Transfer model to new domain.",
                ["Evaporation = earning/saving", "Condensation = investment accumulation", "Precipitation = spending", "Collection = aggregate demand"],
                "Money 'evaporates' from the economy through saving, 'condenses' in investment vehicles, 'precipitates' as spending, and 'collects' in business revenue—flowing continuously like water.", "BIG-Bench"),
            WorkedExample("anal_ex_010", DomainType.ANALOGICAL, "legal", "medium",
                "Past case: Stealing a physical book is theft. Current case: Downloading a pirated ebook. How should precedent apply?",
                "Reason by legal analogy.",
                ["Same: taking without paying", "Different: no physical deprivation", "Key question: Is 'taking' the core issue?"],
                "The analogy holds if we focus on obtaining copyrighted content without authorization. It weakens if we emphasize the lack of physical deprivation (original remains). Courts have generally found the analogy applicable.", "BIG-Bench"),
            WorkedExample("anal_ex_011", DomainType.ANALOGICAL, "negative", "hard",
                "Why is 'employees are family' a problematic analogy?",
                "Identify where analogy breaks down.",
                ["Family: unconditional commitment", "Employment: conditional, transactional", "Metaphor can be manipulative"],
                "The analogy breaks down because families don't lay off members during downturns. Using it can manipulate employees into loyalty without reciprocal commitment. It obscures the fundamentally economic nature of employment.", "BIG-Bench"),
            WorkedExample("anal_ex_012", DomainType.ANALOGICAL, "scientific", "hard",
                "How is natural selection like artificial selection (breeding)?",
                "Scientific analogical reasoning.",
                ["Both: differential reproduction", "Selector: environment vs breeder", "Darwin used this analogy"],
                "Both involve some individuals reproducing more than others, changing population characteristics. Difference: in nature, environment 'selects'; in breeding, humans choose. Darwin used breeding analogy to explain natural selection.", "BIG-Bench"),
            WorkedExample("anal_ex_013", DomainType.ANALOGICAL, "proportional", "medium",
                "Bird : Nest :: Bee : ___?",
                "Animal to home relationship.",
                ["Bird builds and lives in nest", "Bee builds and lives in..."],
                "Hive", "SAT Analogies"),
            WorkedExample("anal_ex_014", DomainType.ANALOGICAL, "function", "medium",
                "What is the 'Achilles heel' of each: Tank? Computer? Democracy?",
                "Apply metaphor across domains.",
                ["Achilles heel = critical vulnerability", "Apply to each system"],
                "Tank: exposed treads/underside. Computer: single point of failure (power, key component). Democracy: voter apathy or misinformation undermining informed consent.", "BIG-Bench"),
            WorkedExample("anal_ex_015", DomainType.ANALOGICAL, "proportional", "hard",
                "Freedom : Tyranny :: Light : ___?",
                "Conceptual opposition relationship.",
                ["Freedom and tyranny are opposites", "Light's opposite is..."],
                "Darkness (or Shadow)", "SAT Analogies"),
        ]

    def _coding_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("code_ex_001", DomainType.CODING, "string", "easy",
                "Write a function to reverse a string.",
                "Use slicing or iteration.",
                ["def reverse_string(s):", "  return s[::-1]"],
                "def reverse_string(s): return s[::-1]", "HumanEval"),
            WorkedExample("code_ex_002", DomainType.CODING, "array", "easy",
                "Find the maximum element in a list.",
                "Use built-in or iterate.",
                ["def find_max(lst):", "  return max(lst)"],
                "def find_max(lst): return max(lst)", "HumanEval"),
            WorkedExample("code_ex_003", DomainType.CODING, "logic", "medium",
                "Check if a number is prime.",
                "Test divisibility up to sqrt(n).",
                ["def is_prime(n):", "  if n < 2: return False", "  for i in range(2, int(n**0.5)+1):", "    if n % i == 0: return False", "  return True"],
                "def is_prime(n): return n > 1 and all(n % i for i in range(2, int(n**0.5)+1))", "HumanEval"),
            WorkedExample("code_ex_004", DomainType.CODING, "recursion", "medium",
                "Calculate Fibonacci number at position n.",
                "Use recursion with memoization.",
                ["def fib(n, memo={}):", "  if n <= 1: return n", "  if n not in memo:", "    memo[n] = fib(n-1) + fib(n-2)", "  return memo[n]"],
                "def fib(n, memo={}): return n if n<=1 else memo.setdefault(n, fib(n-1)+fib(n-2))", "HumanEval"),
            WorkedExample("code_ex_005", DomainType.CODING, "list", "medium",
                "Remove duplicates from a list while preserving order.",
                "Use set to track seen elements.",
                ["def remove_dupes(lst):", "  seen = set()", "  return [x for x in lst if not (x in seen or seen.add(x))]"],
                "def remove_dupes(lst): seen=set(); return [x for x in lst if not (x in seen or seen.add(x))]", "HumanEval"),
            WorkedExample("code_ex_006", DomainType.CODING, "string", "medium",
                "Check if a string is a palindrome.",
                "Compare with reverse.",
                ["def is_palindrome(s):", "  s = s.lower().replace(' ', '')", "  return s == s[::-1]"],
                "def is_palindrome(s): s=s.lower().replace(' ',''); return s==s[::-1]", "HumanEval"),
            WorkedExample("code_ex_007", DomainType.CODING, "sorting", "medium",
                "Implement bubble sort.",
                "Nested loops, swap adjacent elements.",
                ["def bubble_sort(lst):", "  n = len(lst)", "  for i in range(n):", "    for j in range(n-i-1):", "      if lst[j] > lst[j+1]:", "        lst[j], lst[j+1] = lst[j+1], lst[j]", "  return lst"],
                "Bubble sort implementation", "HumanEval"),
            WorkedExample("code_ex_008", DomainType.CODING, "search", "medium",
                "Implement binary search.",
                "Divide search space in half.",
                ["def binary_search(lst, target):", "  lo, hi = 0, len(lst)-1", "  while lo <= hi:", "    mid = (lo+hi)//2", "    if lst[mid] == target: return mid", "    elif lst[mid] < target: lo = mid+1", "    else: hi = mid-1", "  return -1"],
                "Binary search returning index or -1", "HumanEval"),
            WorkedExample("code_ex_009", DomainType.CODING, "hash", "hard",
                "Find two numbers in a list that sum to target.",
                "Use hash map for O(n) solution.",
                ["def two_sum(nums, target):", "  seen = {}", "  for i, n in enumerate(nums):", "    comp = target - n", "    if comp in seen: return [seen[comp], i]", "    seen[n] = i"],
                "Two sum with hash map in O(n)", "HumanEval"),
            WorkedExample("code_ex_010", DomainType.CODING, "dp", "hard",
                "Find the longest common subsequence of two strings.",
                "Use dynamic programming table.",
                ["def lcs(s1, s2):", "  dp = [[0]*(len(s2)+1) for _ in range(len(s1)+1)]", "  for i in range(1,len(s1)+1):", "    for j in range(1,len(s2)+1):", "      if s1[i-1]==s2[j-1]: dp[i][j]=dp[i-1][j-1]+1", "      else: dp[i][j]=max(dp[i-1][j],dp[i][j-1])", "  return dp[-1][-1]"],
                "LCS using DP in O(mn)", "HumanEval"),
            WorkedExample("code_ex_011", DomainType.CODING, "tree", "hard",
                "Find the height of a binary tree.",
                "Use recursion, max of children + 1.",
                ["def tree_height(node):", "  if not node: return 0", "  return 1 + max(tree_height(node.left), tree_height(node.right))"],
                "def tree_height(node): return 0 if not node else 1+max(tree_height(node.left), tree_height(node.right))", "MBPP"),
            WorkedExample("code_ex_012", DomainType.CODING, "graph", "hard",
                "Detect if a graph has a cycle (undirected).",
                "Use DFS with parent tracking.",
                ["def has_cycle(graph, v, visited, parent):", "  visited.add(v)", "  for neighbor in graph[v]:", "    if neighbor not in visited:", "      if has_cycle(graph, neighbor, visited, v): return True", "    elif neighbor != parent: return True", "  return False"],
                "Cycle detection using DFS", "MBPP"),
            WorkedExample("code_ex_013", DomainType.CODING, "regex", "medium",
                "Validate an email address format.",
                "Use regex pattern.",
                ["import re", "def is_valid_email(email):", "  pattern = r'^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$'", "  return bool(re.match(pattern, email))"],
                "Email validation using regex", "MBPP"),
            WorkedExample("code_ex_014", DomainType.CODING, "oop", "medium",
                "Implement a stack with push, pop, and peek.",
                "Use class with list.",
                ["class Stack:", "  def __init__(self): self.items = []", "  def push(self, x): self.items.append(x)", "  def pop(self): return self.items.pop() if self.items else None", "  def peek(self): return self.items[-1] if self.items else None"],
                "Stack class implementation", "MBPP"),
            WorkedExample("code_ex_015", DomainType.CODING, "functional", "medium",
                "Use map and filter to get squares of even numbers from a list.",
                "Chain functional operations.",
                ["def even_squares(lst):", "  return list(map(lambda x: x**2, filter(lambda x: x%2==0, lst)))"],
                "def even_squares(lst): return [x**2 for x in lst if x%2==0]", "MBPP"),
        ]

    def _scientific_examples(self) -> List[WorkedExample]:
        return [
            WorkedExample("sci_ex_001", DomainType.SCIENTIFIC, "hypothesis", "easy",
                "Observation: Plants on the windowsill grow taller than plants in the corner. Form a hypothesis.",
                "Convert observation to testable claim.",
                ["Identify key variable: light", "Form testable prediction"],
                "Hypothesis: Plants exposed to more sunlight grow taller. Prediction: If we move corner plants to the window, they will grow faster.", "SciQ"),
            WorkedExample("sci_ex_002", DomainType.SCIENTIFIC, "variables", "medium",
                "Design experiment: Does music affect plant growth? Identify variables.",
                "Classify variables in experiment.",
                ["Independent: music (presence/type)", "Dependent: plant growth (height/mass)", "Controlled: water, soil, light, plant species"],
                "IV: music exposure. DV: growth measurements. Controls: same water, soil, light, temperature, plant type.", "SciQ"),
            WorkedExample("sci_ex_003", DomainType.SCIENTIFIC, "control", "medium",
                "Testing a new fertilizer. What should the control group receive?",
                "Design appropriate control.",
                ["Control must differ only in IV", "Should receive everything except treatment"],
                "Control group receives water without fertilizer (or standard fertilizer if comparing to new one). All other conditions identical.", "SciQ"),
            WorkedExample("sci_ex_004", DomainType.SCIENTIFIC, "data", "medium",
                "You recorded plant heights: 12, 14, 15, 14, 13 cm. Calculate mean and comment on variability.",
                "Basic statistical analysis.",
                ["Sum: 68, Count: 5", "Mean: 68/5 = 13.6", "Range: 15-12 = 3"],
                "Mean height: 13.6 cm. Range of 3 cm shows moderate variability. Small sample size limits conclusions.", "SciQ"),
            WorkedExample("sci_ex_005", DomainType.SCIENTIFIC, "interpretation", "hard",
                "Experiment shows fertilizer group grew 20% more than control, p=0.03. Interpret.",
                "Interpret statistical result.",
                ["p < 0.05 = statistically significant", "20% = effect size", "Consider practical significance"],
                "The 20% growth increase is statistically significant (p=0.03), unlikely due to chance. This is also practically meaningful. We can conclude fertilizer likely increases growth, though replication is needed.", "SciQ"),
            WorkedExample("sci_ex_006", DomainType.SCIENTIFIC, "error", "medium",
                "Identify potential sources of error in measuring reaction times.",
                "Analyze systematic and random error.",
                ["Human reaction to stimulus", "Equipment precision", "Subject variability"],
                "Errors include: anticipation (starting early), distraction, fatigue effects, equipment lag, and natural human variability. Mitigation: multiple trials, randomized intervals, automated measurement.", "SciQ"),
            WorkedExample("sci_ex_007", DomainType.SCIENTIFIC, "hypothesis", "hard",
                "Scientists notice that antibiotic-resistant bacteria appeared after widespread antibiotic use. Generate two competing hypotheses.",
                "Form alternative hypotheses.",
                ["H1: Antibiotics cause mutations", "H2: Antibiotics select pre-existing resistance", "Design test to distinguish"],
                "H1: Antibiotics cause resistance mutations. H2: Resistant bacteria already existed; antibiotics just killed susceptible ones, selecting for survivors. Test: Expose bacteria briefly—if H1, new resistance appears; if H2, resistance should be instant.", "SciQ"),
            WorkedExample("sci_ex_008", DomainType.SCIENTIFIC, "design", "hard",
                "Design experiment to test if hand washing reduces cold transmission.",
                "Full experimental design.",
                ["Random assignment to groups", "Measure cold incidence", "Control for confounds"],
                "Randomly assign participants to hand-washing or control. Both groups complete symptom diaries. Control for baseline health, age, exposure risk. Measure cold incidence over 3 months. Large sample for power.", "SciQ"),
            WorkedExample("sci_ex_009", DomainType.SCIENTIFIC, "falsification", "hard",
                "How would you falsify the claim 'All swans are white'?",
                "Apply Popperian falsification.",
                ["Cannot prove all swans white", "Can disprove with one counterexample", "Find non-white swan"],
                "Finding a single non-white swan falsifies the claim. This is why 'all X are Y' claims are scientifically risky—one counterexample disproves them. (Black swans were indeed found in Australia.)", "SciQ"),
            WorkedExample("sci_ex_010", DomainType.SCIENTIFIC, "bias", "medium",
                "A drug company tests its own drug and finds it effective. What biases might be present?",
                "Identify research bias.",
                ["Financial conflict of interest", "Publication bias", "Experimenter effects"],
                "Potential biases: funding bias (positive results benefit company), confirmation bias (interpreting ambiguous results favorably), publication bias (hiding negative studies), experimenter effects (unconsciously influencing subjects).", "SciQ"),
            WorkedExample("sci_ex_011", DomainType.SCIENTIFIC, "replication", "medium",
                "A study finds a surprising result. What would increase your confidence in it?",
                "Assess scientific validity.",
                ["Replication by others", "Large sample", "Mechanism explained", "Preregistration"],
                "Confidence increases with: independent replication (especially by skeptics), large sample size, plausible mechanism, preregistered analysis plan, and publication of all data/methods.", "SciQ"),
            WorkedExample("sci_ex_012", DomainType.SCIENTIFIC, "correlation", "medium",
                "Ice cream sales and drowning deaths are correlated. Does ice cream cause drowning?",
                "Distinguish correlation from causation.",
                ["Correlation ≠ causation", "Look for third variable", "Propose mechanism test"],
                "No—both are caused by a third variable: hot weather. Summer increases both ice cream consumption and swimming. To establish causation, we'd need controlled experiments or clear mechanism.", "SciQ"),
            WorkedExample("sci_ex_013", DomainType.SCIENTIFIC, "sample", "medium",
                "You want to study American political opinions. You survey your college campus. What's wrong?",
                "Identify sampling bias.",
                ["College students ≠ all Americans", "Selection bias", "Generalizability limited"],
                "College students are younger, more educated, and often more liberal than the general population. This sample is not representative. Better: random sample of voter registration lists or phone surveys.", "SciQ"),
            WorkedExample("sci_ex_014", DomainType.SCIENTIFIC, "ethics", "hard",
                "You want to study whether stress affects health. Can you deliberately stress participants?",
                "Evaluate research ethics.",
                ["Harm vs benefit", "Informed consent", "Alternatives"],
                "Deliberately causing stress raises ethical concerns (potential harm). Must: minimize harm, get informed consent, allow withdrawal, debrief afterward. Consider alternatives: natural stress observation, mild stressors, retrospective studies.", "SciQ"),
            WorkedExample("sci_ex_015", DomainType.SCIENTIFIC, "revision", "hard",
                "New evidence contradicts established theory. How should science respond?",
                "Understand theory revision.",
                ["Verify new evidence", "Attempt replication", "Modify or replace theory if evidence holds"],
                "Science should: verify the new evidence through replication, check for errors, and if evidence holds, modify the theory minimally or develop new theory. Resistance to anomalies is healthy, but persistent anomalies demand theory change.", "SciQ"),
        ]


# Global instance for easy access
EXAMPLE_LIBRARY = ExampleLibrary()


def get_example(example_id: str) -> Optional[WorkedExample]:
    """Get an example by ID."""
    return EXAMPLE_LIBRARY.get(example_id)


def get_examples_for_domain(domain: DomainType) -> List[WorkedExample]:
    """Get all examples for a domain."""
    return EXAMPLE_LIBRARY.get_by_domain(domain)


def get_random_example(domain: DomainType) -> Optional[WorkedExample]:
    """Get a random example from a domain."""
    return EXAMPLE_LIBRARY.get_random(domain)


if __name__ == "__main__":
    print(f"\nExample Library loaded with {EXAMPLE_LIBRARY.count()} examples\n")
    for domain in DomainType:
        examples = EXAMPLE_LIBRARY.get_by_domain(domain)
        print(f"  {domain.value}: {len(examples)} examples")
    print()
